# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pentagram', '0005_auto_20160719_1138'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='Likes',
        ),
    ]
