# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pentagram', '0006_auto_20160719_1145'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Likes',
            new_name='Like',
        ),
    ]
